---
# tasks file for twingate_connector
- name: Verify docker compose plugin installation.
  package: name=docker-compose state=present


- name: Start twingate connector with inline definition
  docker_compose:
    project_name: "twingate-{{ network }}-{{ connector }}"
    definition:
      services:
        twingate_connector:
          container_name: "{{ connector }}" 
          restart: always
          image: "twingate/connector:1.63.0"
          environment:
            - "TWINGATE_NETWORK={{ network }}"
            - "TWINGATE_ACCESS_TOKEN={{ access_token }}"
            - "TWINGATE_REFRESH_TOKEN={{ refresh_token }}"
            - TWINGATE_LOG_ANALYTICS=v2
            - TWINGATE_LOG_LEVEL=3
          sysctls:
            net.ipv4.ping_group_range: "0 2147483647"
          volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
