---
# tasks file for twingate_connector
- name: Verify docker compose plugin installation.
  package: name=docker-compose state=present


- name: Start twingate connector with inline definition
  docker_compose:
    project_name: "twingate-{{ network }}-{{ connector }}"
    definition:
      services:
        twingate_connector:
          container_name: "{{ connector }}" 
          restart: always
          image: "twingate/connector:latest"
          environment:
            - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
            - TWINGATE_API_ENDPOINT=/connector.stock
            - "TWINGATE_NETWORK={{ network }}"
            - "TWINGATE_ACCESS_TOKEN={{ access_token }}"
            - "TWINGATE_REFRESH_TOKEN={{ refresh_token }}"
            - TWINGATE_LOG_LEVEL=3
          sysctls:
            net.ipv4.ping_group_range: "0 2147483647"
