---
target:
- pi
- ocarina
- fi
- ganondorf

# User some changes will be applied to, e.g. zshrc configuration, permissions etc. 
target_username: rafaelktistakis

packages_ganondorf:
- screen
- tmux
- alpine
- vim
- code
- mosh
- snapd
- git
- at
- dnsmasq
- unrar
- zsh
- apt-transport-https
- ca-certificates
- curl
- software-properties-common
- python3-pip
- virtualenv
- python3-setuptools
- fonts-firacode
- sshpass
- avahi-daemon
- avahi-utils
- avahi-dnsconfd
- avahi-discover
- libnss-mdns
- neofetch
- mc

packages_macintosh:

packages_imac:

packages_macbook:
