---
target:
- pi
- ocarina
- fi
- ganondorf

# User some changes will be applied to, e.g. zshrc configuration, permissions etc. 
target_username: rafaelktistakis

packages_pi_os:
- code

packages_ganondorf:

packages_macintosh:

packages_imac:

packages_macbook:
