---
- hosts: "{{ target }}"
  become: yes
  gather_facts: true
  ignore_errors: yes
  vars_files:
    - config.yml
    - vault.yml
  vars:
    - ansible_become_pass: '{{ su_password }}'

- name: Setting up Raspberry Pi / Pi
  hosts: pi
  become: yes
  collections:
    - rafaelktistakis.pi
    - rafaelktistakis.linux
    - devsec.hardening
  roles:
    - system-setup
    - packages
    # - usbc-gadget
    # - docker
    # - code-tunnel
    # - fstab-umask-fix
#    - os_hardening
  #  - ssh_hardening
  vars_files:
    - config.yml
    - vault.yml
  vars:
    - ansible_become_pass: '{{ su_password }}'
    - packages_remove: 
      - screen
  pre_tasks:
    - name: verify git installation
      package: name=git state=present

- name: Setting up Pi Zero 2 / Ocarina - Fi
  hosts: 
    - ocarina
    - fi
  become: yes
  collections:
    - rafaelktistakis.pi
    - rafaelktistakis.dietpi
    - devsec.hardening
  roles:
    - rafaelktistakis.dietpi.system-setup
  vars_files:
    - config.yml
    - vault.yml
  vars:
    - ansible_become_pass: '{{ su_password }}'
  pre_tasks:
    - name: verify git installation
      package: name=git state=present
    - name: Verify OpenSsh installation
      package: name=openssh-server state=present



  # task:
#    - name: plex setup
#      become: yes
#      import_tasks: playbooks/plex-setup.yml
#    - name: rtorrent setup
#      become: yes
#      import_tasks: playbooks/qbittorrent-setup.yml
  #  - name: Starship setup
  #    become: yes
  #    import_tasks: playbooks/starship-setup.yml
#    - name: Tmux setup
#      become: yes
#      import_tasks: playbooks/tmux-setup.yml
  #  - name: Homebridge setup
  #    become: yes
  #    import_tasks: playbooks/homebridge-setup.yml