---
- hosts: "{{ target }}"
  become: yes
  gather_facts: true
  ignore_errors: yes
  vars_files:
    - config.yml

- name: Setting up Raspberry Pi
  hosts: pi
  become: yes
  collections:
    - rafaelktistakis.pi
    - devsec.hardening
  roles:
    - core
    # - usbc-gadget
    # - docker
    # - code-tunnel
    # - fstab-umask-fix
#    - os_hardening
  #  - ssh_hardening

- name: Setting up Pi Zero 2
  hosts: 
    - fi
    - ocarina
  become: yes
  collections:
    - rafaelktistakis.pi
    - devsec.hardening
  roles:

  vars_files:
    - config.yml

  pre_tasks:
    - name: verify git installation.
      package: name=git state=present

  # task:
#    - name: plex setup
#      become: yes
#      import_tasks: playbooks/plex-setup.yml
#    - name: rtorrent setup
#      become: yes
#      import_tasks: playbooks/qbittorrent-setup.yml
  #  - name: Starship setup
  #    become: yes
  #    import_tasks: playbooks/starship-setup.yml
#    - name: Tmux setup
#      become: yes
#      import_tasks: playbooks/tmux-setup.yml
  #  - name: Homebridge setup
  #    become: yes
  #    import_tasks: playbooks/homebridge-setup.yml