---
- hosts: "{{ target }}"
  become: yes
  gather_facts: true
  ignore_errors: yes
  vars_files:
    - config.yml
    - vault.yml
  vars:
    - ansible_become_pass: '{{ su_password }}'
  pre_tasks:
  - name: verify git installation
    package: name=git state=present
  - name: Verify OpenSsh installation
    package: name=openssh-server state=present

- name: Setting up Raspberry Pi / Pi
  hosts: pi
  become: yes
  collections:
    - rafaelktistakis.pi
    - rafaelktistakis.linux
    - devsec.hardening
  roles:
    - pisetup
    - packages
    - overclock
    - plex
    - starship
    - tmux
    - homebridge
    - qbittorrent
    - usbc-gadget
    - docker
    - code-tunnel
    - fstab-umask-fix
    # - os_hardening
    # - ssh_hardening
  vars_files:
    - config.yml
    - vault.yml
  vars:
    - ansible_become_pass: '{{ su_password }}'
  pre_tasks:
    - name: verify git installation
      package: name=git state=present


- name: Setting up Raspberry Pi 5
  hosts: ganondorf
  become: yes
  collections:
    - rafaelktistakis.pi
    - rafaelktistakis.linux
    - devsec.hardening
  roles:
    - packages
    - pisetup
    - starship
    - tmux
    - docker
    - code-tunnel
    # - os_hardening
    # - ssh_hardening


- name: Setting up Pi Zero 2 / Ocarina - Fi
  hosts: 
    - ocarina
    - fi
  become: yes
  collections:
    - rafaelktistakis.pi
    - rafaelktistakis.dietpi
    - devsec.hardening
  roles:
    - dietpisetup
  vars_files:
    - config.yml
    - vault.yml
  vars:
    - ansible_become_pass: '{{ su_password }}'
