---
# tasks file for user-setup
- name: user setup with groups and shell
  user:
    name: "{{ target_username }}"
    state: present
    create_home: true
    shell: /usr/bin/bash
    groups: 
      - dietpi 
      - sudo 
      - video
