---
# tasks file for microsoft_vscode
# Configure APT to include MS Code repository
- name: Add Microsoft apt Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc 
    state: present

- name: Add VSCode Repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install packages
  apt:
    state: present
    update_cache: true
    name: "{{ packages }}"
  vars:
    packages:
    - code
