---
# tasks file for code-tunnel-server (Self-hosted)

- name: Install Code Server (through bash script)
  shell: curl -fsSL https://code-server.dev/install.sh | sh
  register: task_result
  changed_when: "'Reusing' not in task_result.stdout"

- name: Copy codeserver command prompt
  copy:
    src: codeserver.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    backup: no
