---
# tasks file for tmux
- name: Verify tmux installation.
  package: name=tmux state=present

- name: Copy Tmux conf
  copy:
    src: .tmux.conf
    dest: /home/{{ target_username }}/.tmux.conf
    owner: "{{ target_username }}"
    group: "{{ target_username }}"
    mode: 0644
  notify: Reload Tmux
  register: settings_out

- name: Setting Tmux Plugin Manager
  become_user: "{{ target_username }}"
  git:
    clone: true
    update: true
    force: yes
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: /home/{{ target_username }}/.tmux/plugins/tpm

- block:
  - name: Copy rpi-temp script for dracula tmux
    copy:
      src: rpi_temp.sh
      dest: /home/{{ target_username }}/.tmux/plugins/tmux/scripts/rpi_temp.sh
      owner: "{{ target_username }}"
      group: "{{ target_username }}"
      mode: 0755
  - name: Copy rpi-throttled script for dracula tmux
    copy:
      src: rpi_throttled.sh
      dest: /home/{{ target_username }}/.tmux/plugins/tmux/scripts/rpi_throttled.sh
      owner: "{{ target_username }}"
      group: "{{ target_username }}"
      mode: 0755
  rescue:
  - name: Print custom message before failing the host
    fail:
      msg: "The above script is for the dracula tmux theme. Running it requires to have installed the plugins first. That's done by ctl-T + I in a tmux session"
    ignore_errors: true

- name: Starting Tmux session to reload new settings
  become_user: "{{ target_username }}"
  shell: tmux new -d
  when: settings_out.changed
