---
# tasks file for tmux
- name: Verify tmux installation.
  package: name=tmux state=present

- name: Copy Tmux conf
  copy:
    src: .tmux.conf
    dest: /home/{{ target_username }}/.tmux.conf
    owner: "{{ target_username }}"
    group: "{{ target_username }}"
    mode: 0644
  notify: Reload Tmux

- name: Setting Tmux Plugin Manager
  become_user: "{{ target_username }}"
  git:
    clone: true
    update: true
    force: yes
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: /home/{{ target_username }}/.tmux/plugins/tpm

- name: Copy rpi-temp script for dracula tmux
  copy:
    src: rpi_temp.sh
    dest: /home/{{ target_username }}/.tmux/plugins/tmux/scripts/rpi_temp.sh
    owner: "{{ target_username }}"                                                                              
    group: "{{ target_username }}"                                                                              
    mode: 0755

- name: Copy rpi-throttled script for dracula tmux
  copy:
    src: rpi_throttled.sh
    dest: /home/{{ target_username }}/.tmux/plugins/tmux/scripts/rpi_throttled.sh
    owner: "{{ target_username }}"                                  
    group: "{{ target_username }}"                                  
    mode: 0755

