---
# tasks file for packages
- name: Upgrade all packages
  apt:
    name: '*'
    update_cache: true
    autoremove: true
    state: latest

- name: Install packages from list
  apt:
    state: present
    update_cache: true
    name: "{{ packages_install }}"

- name: Remove packages as configured
  apt:
    state: absent
    update_cache: true
    name: "{{ packages_remove }}"