#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux. It does not account for X11 forwarding
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
